version: "3"
services:
  pg:
    image: "postgres:12"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: docker
    container_name: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data

  app:
    container_name: patchmaster-app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - pg
